In [145]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [146]:
df=sns.load_dataset('iris')

In [147]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [148]:
df.shape

(150, 5)

In [149]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [150]:
from sklearn.model_selection import train_test_split

In [151]:
x=df.drop('species', axis=1)
y=df['species']

In [152]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [153]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [154]:
from sklearn.neighbors import KNeighborsClassifier

In [155]:
model_knn=KNeighborsClassifier(n_neighbors=5)

In [156]:
model_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [157]:
model_knn.score(x_test,y_test)

0.98

In [158]:
from sklearn.svm import SVC

In [159]:
model_svc=SVC(gamma='auto')

In [160]:
model_svc.fit(x_train,y_train)

SVC(gamma='auto')

In [161]:
model_svc.score(x_test,y_test)

1.0

In [162]:
from sklearn.model_selection import GridSearchCV

In [163]:
classifier=GridSearchCV((model_svc),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
}, cv=5, return_train_score=False)

In [164]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [165]:
classifier.cv_results_

{'mean_fit_time': array([0.0040514 , 0.00390768, 0.00360942, 0.00360303, 0.00366879,
        0.00347056, 0.00426402, 0.00378242]),
 'std_fit_time': array([2.97160058e-04, 4.59636740e-04, 1.36588670e-04, 6.27794466e-05,
        5.91620223e-05, 7.25644640e-05, 6.52304999e-04, 1.83242235e-04]),
 'mean_score_time': array([0.00338235, 0.00275974, 0.00262585, 0.00277848, 0.00274653,
        0.00268335, 0.00295124, 0.00312381]),
 'std_score_time': array([1.16770826e-03, 1.30770572e-04, 1.86897454e-04, 3.28399935e-05,
        1.00680572e-04, 1.52145161e-04, 2.65762768e-04, 5.61360388e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [166]:
results=pd.DataFrame(classifier.cv_results_)

In [167]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004051,0.000297,0.003382,0.001168,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003908,0.000460,0.002760,0.000131,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003609,0.000137,0.002626,0.000187,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003603,0.000063,0.002778,0.000033,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003669,0.000059,0.002747,0.000101,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003471,0.000073,0.002683,0.000152,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.004264,0.000652,0.002951,0.000266,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003782,0.000183,0.003124,0.000561,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [168]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [169]:
from sklearn.model_selection import RandomizedSearchCV

In [170]:
classifier_r=RandomizedSearchCV((model_svc),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
}, n_iter=4, cv=5, return_train_score=False)

In [171]:
classifier_r.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [172]:
results_r=pd.DataFrame(classifier_r.cv_results_)

In [173]:
results_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004515,0.001554,0.002891,0.000114,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.9,0.966667,1.0,0.973333,0.038873,1
1,0.003706,0.000115,0.003077,0.000341,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.9,0.900000,1.0,0.960000,0.048990,4
2,0.003654,0.000138,0.002770,0.000163,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.9,0.933333,1.0,0.966667,0.042164,3
3,0.003791,0.000151,0.003120,0.000549,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.9,0.966667,1.0,0.966667,0.036515,2

In [174]:
results_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1       30       linear         0.960000
2       20       linear         0.966667
3       20          rbf         0.966667